language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/golang/dep/...
  - go get github.com/mattn/goveralls
install:
  - $GOPATH/bin/dep ensure
script:
  - go test -covermode=count -coverprofile=profile.cov
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci -repotoken=t1wbCOVfLQvhfDZB1ABdudwhcN6lcHGqs